//mainwindow.cpp
#include "mainwindow.h"
#include "./ui_mainwindow.h"

MainWindow::MainWindow(QWidget *parent)
    : QMainWindow(parent)
    , ui(new Ui::MainWindow)
{
    ui->setupUi(this); //setup ui according to mainwindow.ui
}

MainWindow::~MainWindow() //constructor for main window
{
    //boilerplate, dont know what it does, generated by qtcreator
    delete ui;
}


void MainWindow::on_input1SubmitButton_clicked() //run when submit button for input 1 pushed
{
    //clear error msg
    ui->input1ErrorDisplay->clear();

    switch (ui->input1FormatSelector->currentIndex()) { //switch to run different functions depending on format selection index

    case 0: //binary
        //run setBinaryValue, display error msg and return on fail
        if (not input1.setBinaryValue(ui->input1PlainTextEdit->toPlainText())) {
            ui->input1ErrorDisplay->setText("Formatting Error: expecting binary");
            return;
        }
        break;

    case 1: //decimal
        //run setDecimalValue, display error msg and return on fail
        if (not input1.setDecimalValue(ui->input1PlainTextEdit->toPlainText())) {
            ui->input1ErrorDisplay->setText("Formatting Error: expecting decimal");
            return;
        }
        break;

    case 2: //hex
        //run setHexValue, display error msg and return on fail
        if (not input1.setHexValue(ui->input1PlainTextEdit->toPlainText())) {
            ui->input1ErrorDisplay->setText("Formatting Error: expecting hex");
            return;
        }
        break;

    case 3: //SEM
        //run setSEMValue, display error msg and return on fail
        if (not input1.setSEMValue(ui->input1PlainTextEdit->toPlainText())) {
            ui->input1ErrorDisplay->setText("Formatting Error: expecting SEM");
            return;
        }
        break;

    }

    //display results
    ui->input1BinaryDisplay->setText(input1.getBinaryText());
    ui->input1DecimalDisplay->setText(input1.getDecimalText());
    ui->input1HexDisplay->setText(input1.getHexText());
    ui->input1SEMDisplay->setText(input1.getSEMText());
}
