#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <QMainWindow>
#include "floatingpoint.h"

//boilerplate, dont know what it does, generated by qtcreator
QT_BEGIN_NAMESPACE
namespace Ui {
class MainWindow;
}
QT_END_NAMESPACE

//main window object
class MainWindow : public QMainWindow
{
    //boilerplate, dont know what it does, generated by qtcreator
    Q_OBJECT

public:
    //boilerplate, dont know what it does, generated by qtcreator
    explicit MainWindow(QWidget *parent = nullptr);
    ~MainWindow() override;

private slots:

    //functions to handle user interaction
    void on_input1SubmitButton_clicked();

    void on_operationSubmitButton_clicked();

    void on_input2SubmitButton_clicked();

    void on_input1FormatSelector_currentIndexChanged(int index);

    void on_input2FormatSelector_currentIndexChanged(int index);

private:
    //boilerplate, dont know what it does, generated by qtcreator
    Ui::MainWindow *ui;

    //custom float objects that handle conversion to and from text
    floatingPoint input1;
    floatingPoint input2;
    floatingPoint output;
};
#endif // MAINWINDOW_H
