//mainwindow.cpp
#include "mainwindow.h"
#include "./ui_mainwindow.h"

MainWindow::MainWindow(QWidget *parent)
    : QMainWindow(parent)
    , ui(new Ui::MainWindow)
{
    ui->setupUi(this); //setup ui according to mainwindow.ui
}

MainWindow::~MainWindow() //constructor for main window
{
    //boilerplate, dont know what it does, generated by qtcreator
    delete ui;
}


void MainWindow::on_input1SubmitButton_clicked() //run when submit button for input 1 pushed
{
    //clear error msg
    ui->input1ErrorDisplay->clear();

    switch (ui->input1FormatSelector->currentIndex()) { //switch to run different functions depending on format selection index

    case 0: //binary
        //run setBinaryValue, display error msg and return on fail
        if (not input1.setBinaryValue(ui->input1PlainTextEdit->toPlainText())) {
            ui->input1ErrorDisplay->setText("Formatting Error: expecting binary");
            return;
        }
        break;

    case 1: //decimal
        //run setDecimalValue, display error msg and return on fail
        if (not input1.setDecimalValue(ui->input1PlainTextEdit->toPlainText())) {
            ui->input1ErrorDisplay->setText("Formatting Error: expecting decimal");
            return;
        }
        break;

    case 2: //hex
        //run setHexValue, display error msg and return on fail
        if (not input1.setHexValue(ui->input1PlainTextEdit->toPlainText())) {
            ui->input1ErrorDisplay->setText("Formatting Error: expecting hex");
            return;
        }
        break;

    case 3: //SEM
        //run setSEMValue, display error msg and return on fail
        if (not input1.setSEMValue(ui->input1PlainTextEdit->toPlainText())) {
            ui->input1ErrorDisplay->setText("Formatting Error: expecting SEM");
            return;
        }
        break;

    }

    //display results
    ui->input1BinaryDisplay->setText(input1.getBinaryText());
    ui->input1DecimalDisplay->setText(input1.getDecimalText());
    ui->input1HexDisplay->setText(input1.getHexText());
    ui->input1SEMDisplay->setText(input1.getSEMText());
}


void MainWindow::on_input2SubmitButton_clicked()
{
    //clear error msg
    ui->input2ErrorDisplay->clear();

    switch (ui->input2FormatSelector->currentIndex()) { //switch to run different functions depending on format selection index

    case 0: //binary
        //run setBinaryValue, display error msg and return on fail
        if (not input2.setBinaryValue(ui->input2PlainTextEdit->toPlainText())) {
            ui->input2ErrorDisplay->setText("Formatting Error: expecting binary");
            return;
        }
        break;

    case 1: //decimal
        //run setDecimalValue, display error msg and return on fail
        if (not input2.setDecimalValue(ui->input2PlainTextEdit->toPlainText())) {
            ui->input2ErrorDisplay->setText("Formatting Error: expecting decimal");
            return;
        }
        break;

    case 2: //hex
        //run setHexValue, display error msg and return on fail
        if (not input2.setHexValue(ui->input2PlainTextEdit->toPlainText())) {
            ui->input2ErrorDisplay->setText("Formatting Error: expecting hex");
            return;
        }
        break;

    case 3: //SEM
        //run setSEMValue, display error msg and return on fail
        if (not input2.setSEMValue(ui->input2PlainTextEdit->toPlainText())) {
            ui->input2ErrorDisplay->setText("Formatting Error: expecting SEM");
            return;
        }
        break;

    }

    //display results
    ui->input2BinaryDisplay->setText(input2.getBinaryText());
    ui->input2DecimalDisplay->setText(input2.getDecimalText());
    ui->input2HexDisplay->setText(input2.getHexText());
    ui->input2SEMDisplay->setText(input2.getSEMText());
}

void MainWindow::on_operationSubmitButton_clicked()
{
    //clear error msg
    ui->outputErrorDisplay->clear();

    switch (ui->operationSelectorComboBox->currentIndex()) { //switch to run different functions depending on format selection index

    case 0: //addition
        output.setValue(input1.getValue() + input2.getValue());
        break;

    case 1: //subtraction
        output.setValue(input1.getValue() - input2.getValue());
        break;

    case 2: //multiplication
        output.setValue(input1.getValue() * input2.getValue());
        break;
    }

    //display results
    ui->outputBinaryDisplay->setText(output.getBinaryText());
    ui->outputDecimalDisplay->setText(output.getDecimalText());
    ui->outputHexDisplay->setText(output.getHexText());
    ui->outputSEMDisplay->setText(output.getSEMText());
}


void MainWindow::on_input1FormatSelector_currentIndexChanged(int index)
{

    switch (ui->input1FormatSelector->currentIndex()) { //switch to run different functions depending on format selection index

    case 0: //binary
        //run setBinaryValue, display error msg and return on fail
        if (not input1.setBinaryValue(ui->input1PlainTextEdit->toPlainText())) {
            ui->input1ErrorDisplay->setText("Format: 10101010101010101010101010101010");
            return;
        }
        break;

    case 1: //decimal
        //run setDecimalValue, display error msg and return on fail
        if (not input1.setDecimalValue(ui->input1PlainTextEdit->toPlainText())) {
            ui->input1ErrorDisplay->setText("Format: ...1.0...");
            return;
        }
        break;

    case 2: //hex
        //run setHexValue, display error msg and return on fail
        if (not input1.setHexValue(ui->input1PlainTextEdit->toPlainText())) {
            ui->input1ErrorDisplay->setText("TODO");
            return;
        }
        break;

    case 3: //SEM
        //run setSEMValue, display error msg and return on fail
        if (not input1.setSEMValue(ui->input1PlainTextEdit->toPlainText())) {
            ui->input1ErrorDisplay->setText("Format: -1^(SIGN)x1+0.MANTISSAx2^(EXPONENT-127)");
            return;
        }
        break;

    }
}


void MainWindow::on_input2FormatSelector_currentIndexChanged(int index)
{

    switch (ui->input2FormatSelector->currentIndex()) { //switch to run different functions depending on format selection index

    case 0: //binary
        //run setBinaryValue, display error msg and return on fail
        if (not input2.setBinaryValue(ui->input2PlainTextEdit->toPlainText())) {
            ui->input2ErrorDisplay->setText("Format: 10101010101010101010101010101010");
            return;
        }
        break;

    case 1: //decimal
        //run setDecimalValue, display error msg and return on fail
        if (not input2.setDecimalValue(ui->input2PlainTextEdit->toPlainText())) {
            ui->input2ErrorDisplay->setText("Format: ...1.0...");
            return;
        }
        break;

    case 2: //hex
        //run setHexValue, display error msg and return on fail
        if (not input2.setHexValue(ui->input2PlainTextEdit->toPlainText())) {
            ui->input2ErrorDisplay->setText("TODO");
            return;
        }
        break;

    case 3: //SEM
        //run setSEMValue, display error msg and return on fail
        if (not input2.setSEMValue(ui->input2PlainTextEdit->toPlainText())) {
            ui->input2ErrorDisplay->setText("Format: -1^(SIGN)x1+0.MANTISSAx2^(EXPONENT-127)");
            return;
        }
        break;

    }
}

